---
sudo: true
language: python
dist: xenial

install:
  - sudo rm -f /etc/ImageMagick-6/policy.xml
  - sudo apt-get install xvfb libreoffice libfile-mimeinfo-perl inkscape poppler-utils qpdf imagemagick libimage-exiftool-perl ufraw-batch ffmpeg ghostscript -y
  - pip install xvfbwrapper
  - pip install pytest
  - pip install -U -r requirements.txt

before_script:
  - export DISPLAY=:99.0
  - which Xvfb
  - Xvfb :99 -screen 0 1x1x16 > /dev/null 2>&1 &
  - sudo mkdir -p /tmp/ && sudo chmod 0777 /tmp/

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

script:
  - pytest --ignore venv -W ignore::DeprecationWarning
